// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfbIfnx1BZTb6dI83D32WwMl96fYI0Z8U',
    appId: '1:515468558659:web:ec9c51816551b85d302ff6',
    messagingSenderId: '515468558659',
    projectId: 'smartpos-erp-9e617',
    authDomain: 'smartpos-erp-9e617.firebaseapp.com',
    storageBucket: 'smartpos-erp-9e617.firebasestorage.app',
    measurementId: 'G-DS77NMY3FN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZtEoVk747HvV9qNOUNdprapJfGhE9KSY',
    appId: '1:515468558659:android:90f8768a30b135f2302ff6',
    messagingSenderId: '515468558659',
    projectId: 'smartpos-erp-9e617',
    storageBucket: 'smartpos-erp-9e617.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4LnVwm-3J8e_rvl-J9cks8pEe2NsbwdM',
    appId: '1:515468558659:ios:c0e6ac6e04cf2f07302ff6',
    messagingSenderId: '515468558659',
    projectId: 'smartpos-erp-9e617',
    storageBucket: 'smartpos-erp-9e617.firebasestorage.app',
    iosBundleId: 'com.example.smartposErpV2',
  );
}
